### ISSUE TITLE
Licensing clarification

### ISSUE THREAD

**Issue by api-haus** [wewrere41/Unity-GetComponent-Generator#1]
Hello @wewrere41 .

Thank you for publishing your original Medium article and this project that sets a clear example on a rather obscure topic of Roslyn Source Generators in Unity.

I could not find a licensing notice on your Medium blog or in this project. Would you consider this code to be licensed under MIT license?

**Comment by wewrere41** [comment]
First of all, thanks. I am inexperienced with open source/licensing.  Also, thank you for alerting me. 
82c8076e59b9cedac89e009dbe94309611bfa823

**Comment by api-haus** [comment]
@wewrere41 Thanks again. This will allow anyone to use the Generator in any type of project legally.
